name: Integration test

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8001:8000

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm run install-all

      - name: Build app
        run: npm run build

      - name: Run integration tests
        run: npm run test:integration

      - name: Run UI tests
        run: | #pragma: allowlist secret
          cd tests/ui-tests
          touch .env
          echo "PRE_OR_POST_DEPLOY=pre" >> .env
          echo "PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/" >> .env
          echo "SESSION_SECRET=secret" >> .env
          echo "SESSION_EXPIRY=1800000" >> .env
          echo "DYNAMO_ENDPOINT=http://127.0.0.1:8001" >> .env
          echo "AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE" >> .env
          echo "AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY" >> .env
          echo "AWS_REGION=eu-west-2" >> .env
          npm run test
