name: Validation

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  validation-checks:
    permissions:
      contents: read
    name: Validation checks
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Check ESLint and Prettier
        run: npm run lint

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a

      - name: Lint Terraform
        run: npm run tflint

      - name: Setup SAM
        if: github.actor != 'dependabot[bot]'
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          use-installer: true

      - name: Run SAM validate + cfnlint
        if: github.actor != 'dependabot[bot]'
        run: sam validate -t template.yaml --region eu-west-2 --lint
